DELETE http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123-456789"
}


###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "111-222333"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "No Number"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "000-000000"
}


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jane Test",
  "number": "123-123123"
}

###
GET  http://localhost:3001/api/persons/:id

###
GET  http://localhost:3001/info


### test with valid ID
GET http://localhost:3001/api/persons/6808c2edeba727b171fea707
